version: 1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\bin\**\*.vsix'
  name: DebuggerStepThroughRemover.vsix
- path: '**\DebuggerStepThroughRemover.1.0.*.*.nupkg'
  name: DebuggerStepThroughRemover.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: FgO+hO78M4KmYjCzv88xo/PsLLehbnzYGsEYFkhk2tmMKJMl632frvthC9nj8tAl